language: java
jdk: oraclejdk8
notifications:
 email:
  on_success: never # default: change
  on_failure: always # default: always
env: 
 - TEST_DIR=DbApp
script:
  - cd $TEST_DIR
  - mvn test
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
