language: java
jdk: oraclejdk8
script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
  - mvn verify
install: true
notifications:
 email:
  on_success: never # default: change
  on_failure: always # default: always



