language: java
jdk: oraclejdk8
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
script: cd DBApp
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
